CREATE DATABASE STUDENT_RECORDS;
USE STUDENT_RECORD


CREATE TABLE STUDENT_INFORMATION(STUDENT_ID INT PRIMARY KEY IDENTITY(1,1), NAME VARCHAR(50) NOT NULL,  AGE INT, GENDER VARCHAR(10), SUBJECT VARCHAR(50));

INSERT INTO STUDENT_INFORMATION( NAME, AGE, GENDER, SUBJECT)
VALUES ('MARYJANE',20,'FEMALE','ENGLISH'),
       ( 'JOHN', 27,'MALE' ,'IGBO'),
	   ( 'FRAMK', 30, 'MALE', 'BIOLOGY'),
	    ( 'JANE', 20,'FEMALE' ,'CHEMISTRY'),
	   ( 'BROWN', 30,'MALE', 'BIOLOGY'),
	   (  'ADA', 19, 'FEMALE','PHYSICS');

SELECT STUDENT_ID FROM STUDENT_INFORMATION;
SELECT * FROM STUDENT_INFORMATION;

EXEC sp_rename 'STUDENT_INFORMATION.SUBJECT', 'COURSE';

SELECT * FROM STUDENT_INFORMATION;

ALTER TABLE STUDENT_INFORMATION
DROP COLUMN AGE;

SELECT * FROM STUDENT_INFORMATION;



CREATE TABLE HEALTH_RECORD(STUDENT_ID INT PRIMARY KEY IDENTITY(1,1), BLOODGROUP VARCHAR(3),  WEIGHT DECIMAL(5,2), HEIGHT DECIMAL(5,2));

INSERT INTO HEALTH_RECORD(BLOODGROUP, WEIGHT, HEIGHT)
VALUES ( 'O', 101.23, 120.18),
       ( 'A+', 120.13, 110.38),
	   ( 'AB+', 138.23, 105.18),
	   ( 'O-', 101.23, 120.18);


SELECT STUDENT_ID FROM HEALTH_RECORD;
SELECT * FROM HEALTH_RECORD;


CREATE TABLE PERFORMANCE(STUDENT_ID INT PRIMARY KEY IDENTITY(1,1), SCORE INT DEFAULT '0',  GRADE INT);

INSERT INTO PERFORMANCE(SCORE, GRADE)
VALUES (50, 55),
        ('' , 70),
		(100, 45),
		(89, 90),
		(40, 62),
		('', 92);

SELECT STUDENT_ID FROM PERFORMANCE;
SELECT * FROM PERFORMANCE;




	   






