SELECT DISTINCT YEARLY_INCREMENT FROM Salary;

SELECT *, CASE WHEN YEARLY_INCREMENT BETWEEN 2000 AND 2500 THEN 'LOW'
                              WHEN YEARLY_INCREMENT BETWEEN 3000 AND 5000 THEN 'MEDIUM'
							  ELSE 'HIGH'
							  END AS SALARY_GROUP
							  FROM SALARY;

SELECT * FROM SALARY;

/* Salaries less than 1million showing in Ascending Order*/

SELECT *
FROM Salary
WHERE Base <1000000 ORDER BY empID ASC;
